name: Import and Deploy API Proxy

on:
  push:
    branches:
      - main

jobs:
  import_and_deploy_proxy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    
    - name: Import API Proxy
      run: |
        curl -X POST \
        -H "Content-Type: multipart/form-data" \
        -H "Authorization: Bearer ${{ secrets.PROD_APIGEE_BEARER_TOKEN }}" \
        -F "file=@@final-import-and-deployment/apiproxy" \
        "https://api.enterprise.apigee.com/v1/organizations/zebra-prod/apis?action=import"


    
