name: Import and Deploy API Proxy

on:
  push:
    branches:
      - main

jobs:
  import_and_deploy_proxy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Import API Proxy
      run: |
        # Replace 'api_proxy.zip' with the name of your API proxy zip file
        zip_file="api_proxy.zip"
        # Replace 'zebra-prod' with your organization name
        org_name="zebra-prod"
        # Replace 'stage' with your environment name
        env_name="stage"
        
        # Import the API proxy
        http POST "https://api.enterprise.apigee.com/v1/organizations/$org_name/apis?action=import" \
          "Authorization: Bearer ${{ secrets.PROD_APIGEE_BEARER_TOKEN }}" \
          file@"$zip_file" \
          validate:=true

    - name: Deploy API Proxy to Stage
      run: |
        # Replace 'zebra-prod', 'api_proxy', and '1' with your organization name, API proxy name, and revision number respectively
        http POST "https://api.enterprise.apigee.com/v1/organizations/zebra-prod/apis/Savanna-API-Apigee-FinOps/revisions/1/deployments?action=deploy&env=$env_name" \
          "Authorization: Bearer ${{ secrets.PROD_APIGEE_BEARER_TOKEN }}"
