name: Import and Deploy API Proxy

on:
  push:
    branches:
      - main

jobs:
  import_proxy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Create API bundle
      run: zip -r proxy.zip apiproxy
    
    - name: Upload API Proxy Bundle
        
      run: |
        curl -X POST \
        -H "Content-Type: multipart/form-data" \
        -H "Authorization: Bearer ${{ secrets.PROD_APIGEE_BEARER_TOKEN }}" \
        -F "file=@apiproxy.zip" \
        "https://api.enterprise.apigee.com/v1/organizations/zebra-prod/apis/Savanna-API-Apigee-FinOps/revisions/16"

    

    
