name: Import and Deploy API Proxy

on:
  push:
    branches:
      - main

jobs:
  import_and_deploy_proxy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Import API Proxy
      run: |
        # Replace 'apiproxy.zip' with the name of your API proxy zip file
        zip_file="apiproxy.zip"
        # Replace 'zebra-prod' with your organization name
        org_name="zebra-prod"
        # Replace 'stage' with your environment name
        env_name="stage"
        
        # Import the API proxy using curl
        curl -X POST \
          -H "Authorization: Bearer ${{ secrets.PROD_APIGEE_BEARER_TOKEN }}" \
          -F "file=@$zip_file" \
          "https://api.enterprise.apigee.com/v1/organizations/$org_name/apis?action=import&validate=true"

    - name: Deploy API Proxy to Stage
      run: |
        # Replace 'zebra-prod', 'api_proxy', and '1' with your organization name, API proxy name, and revision number respectively
        curl -X POST \
          -H "Authorization: Bearer ${{ secrets.PROD_APIGEE_BEARER_TOKEN }}" \
          "https://api.enterprise.apigee.com/v1/organizations/$org_name/apis/api_proxy/revisions/1/deployments?action=deploy&env=$env_name"
