name: Deploy API Proxy

on:
  push:
    branches:
      - main

jobs:
  deploy_api_proxy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy API Proxy
        run: |
          curl --fail -X POST \
            -H "Authorization: Bearer ${{ secrets.PROD_APIGEE_BEARER_TOKEN }}" \
            "https://api.enterprise.apigee.com/v1/organizations/zebra-prod/environments/stage/apis/Savanna-API-Apigee-FinOps/revisions/16/deployments"
